// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://antvutwneolxsxdrtmxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudHZ1dHduZW9seHN4ZHJ0bXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTQzNDgsImV4cCI6MjA2ODM3MDM0OH0.bPcdi9VgF82tcR_R6x-UtuKdaEXkqLzxXMt74omNjG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});